[package]
name = "pulse-core"
version.workspace = true
edition.workspace = true

[dependencies]
pulse-crypto = { path = "../pulse-crypto" }
pulse-protocol = { path = "../pulse-protocol" }
thiserror.workspace = true
tracing.workspace = true
sha2.workspace = true
uuid.workspace = true

[dev-dependencies]
proptest.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
rand.workspace = true
